### ISSUE TITLE
Problem in configuration

### ISSUE THREAD

**Issue by deveshmirani15** [checkmarx-ts/checkmarx-python-sdk#104]
Hey, Can someone tell me, how to configure checkmark SCA , It asks for account info in config.py. I am unable to understand what exactly it is.

**Comment by cx-happy-yang** [comment]
Hi @deveshmirani15 ,

You can [enable debug mode,](https://github.com/checkmarx-ts/checkmarx-python-sdk#debug-mode) to check how the python sdk load the configurations.

In config.py, there is the default configuration.

```Python
config_default = {
    "access_control_url": "https://platform.checkmarx.net",
    "server": "https://api-sca.checkmarx.net",
    "account": None,
    "username": None,
    "password": None,
    "scope": "sca_api access_control_api",
    "timeout": 60,
    "verify": False,
    "cert": None,
}
```

But the default one will be oveerride by readming from config.ini, config.json, environment variable, and command line argument. See more info, from function [get_config](https://github.com/checkmarx-ts/checkmarx-python-sdk/blob/master/CheckmarxPythonSDK/utilities/configUtility.py#L213).
