### ISSUE TITLE
Issue with environement variables

### ISSUE THREAD

**Issue by Aloywick** [checkmarx-ts/checkmarx-python-sdk#109]
Hello,

I've been using the checkmarx SDK to get vulnerabilities in our projects packages using a lambda function on AWS but the sdk doesn't seem to take into account the environment variables set, namely:
- username
- password
- client_secret
I've already checked in the logs of my lambda function that these variables are properly set but apparently the checkmarx SDK doesn't account for them.

Thank you!
Alec

**Comment by cx-happy-yang** [comment]
Hi @Aloywick ,

For the environment variable please use the following for CxSAST:

- cxsast_base_url
- cxsast_username
- cxsast_password
- cxsast_grant_type
- cxsast_scope
- cxsast_client_id
- cxsast_client_secret

Please try it and let me know how it works.

Happy

**Comment by Aloywick** [comment]
I've checked and the env variables are set with the appropriate name. Must all variables be set or only part of them?

**Comment by cx-happy-yang** [comment]
Only part of them. You can check the function definition from [here](https://github.com/checkmarx-ts/checkmarx-python-sdk/blob/6cc2a9b715791688b2022aa8d1e7e29552f2ebbc/CheckmarxPythonSDK/utilities/configUtility.py#LL213C15-L213C15).

So you will understand how the configuration is loaded.
