### ISSUE TITLE
get_users_by_groups in CheckmarxPythonSDK\CxOne\AccessControlAPI\api.py Doesn't Work

### ISSUE THREAD

**Issue by jbnable** [checkmarx-ts/checkmarx-python-sdk#114]
def get_users_by_groups(realm, group_id) -> List[AstUser]:  Doesn't work, need to use def get_group_members from GroupsAPI.py instead.

Can we get get_group_members added to CxOne\AccessControlAPI\api.py?

Thanks!

**Comment by cx-happy-yang** [comment]
I will look into the issue.

**Comment by cx-happy-yang** [comment]
Hi @jbnable ,

I run the test it works for me.

See the test code from tests/CxOne/AccessControlAPI/test_access_control_api.py  function test_get_users_by_groups

Here is the screenshot:
![image](https://github.com/checkmarx-ts/checkmarx-python-sdk/assets/30431255/1593e0ed-e709-4142-8ca1-06842636f3cd)

**Comment by cx-happy-yang** [comment]
Unfortunately get_group_members from GroupsAPI.py only return an empty list. This one does not work. I will create internal support case to handle the issue.

Please use get_users_by_groups from CxOne AccessControlAPI

**Comment by jbnable** [comment]
Hi @HappyY19, I'm trying to get get_users_by_groups to work but I keep getting a 403 error. Can you describe what permissions are required to make the call?

**Comment by cx-happy-yang** [comment]
Hi @jbnable ,

Follow the [SCA document](https://checkmarx.com/resource/documents/en/34965-19168-roles.html), I think you will need at least User Manager or Access Control Manager role to use this API.

I am using an internal account with Admin role, so this API works for me.

Sadly I can not play with the roles in my account as I don't have the permission. So I can not give you the exactly answer. You might need to create a support case, or you can just try the User Manager Role or Access Control Manager Role.

**Comment by jbnable** [comment]
Added permissions manage-groups and manage-users and it works now, thanks!

**Comment by jbnable** [comment]
Closing as completed, get_users_by_groups works as long as the service account has manage-groups and manage-users permissions.
