### ISSUE TITLE
CxError / HTTP 415 error with 0.8.5

### ISSUE THREAD

**Issue by csassaman-els** [checkmarx-ts/checkmarx-python-sdk#131]
Upgrading from 0.8.4 to 0.8.5 causes API calls to return a 415 error.

It looks like this commit removed the `application/json` setting from the request headers:

https://github.com/checkmarx-ts/checkmarx-python-sdk/commit/3d63f0d118fb5995e5ea70bba7de3d655b021899

Could this be resolved in a future release? We are sticking with 0.8.4 for now. Thanks!

**Comment by cx-happy-yang** [comment]
@csassaman-els   Please upgrade to v0.8.6.
