### ISSUE TITLE
SCA authentication doesn’t work for European accounts

### ISSUE THREAD

**Issue by valrieux** [checkmarx-ts/checkmarx-python-sdk#14]
The target URL to request token is hardcoded with US server: https://github.com/checkmarx-ts/checkmarx-python-sdk/blob/master/CheckmarxPythonSDK/CxScaApiSDK/authHeaders.py#L25
Thus, with a European we always get
> {"error":"invalid_grant","error_description":"invalid_username_or_password"}

**Comment by cx-happy-yang** [comment]
Hi @valrieux ,

Thanks for reporting the bug.

I will fix the bug today. Make the url configurable.

Thanks.

**Comment by cx-happy-yang** [comment]
Hi @valrieux ,

Please upgrade to the latest version 0.2.3.

The CxSCA section in config file is like:
[CxSCA]
access_control_url = https://eu.platform.checkmarx.net
server = https://eu.api-sca.checkmarx.net
account = ***
username = ***
password = ***

Or you can use command line option, or environment variable with "cxsca_access_control_url=https://eu.platform.checkmarx.net" 

Let me how it works.

Thanks.

**Comment by cx-happy-yang** [comment]
Hi @valrieux ,

Let me know if I can close the issue.

Thanks.

**Comment by valrieux** [comment]
Hello @HappyY19 ,

Thank you for the correction, it is ok now.
