### ISSUE TITLE
Bug: assign_ticket_to_scan_result()

### ISSUE THREAD

**Issue by Apipia** [checkmarx-ts/checkmarx-python-sdk#15]
I am having trouble understanding how this function works and would love it if someone could explain it to me.

Scans contain Queries, queries contains results, and results contains path nodes. 
If I comment a specific item in Checkmarx, I'm commenting, essentially, on one of the results within a query. 
However, many findings have the same "result_id" (I'm looking at the xml output from generating a report). 
So if the function takes a result_id, how does know which particular instance of the finding? Each "Path" object has an sid, even that is not _completely_ unique either. 

What is this "result_id", and how does that map to a row in the CX UI when viewing a scan?

**Comment by Apipia** [comment]
Okay I figured it out, Result_ID is actually the `ResultId + _ + ScanId`. This might be useful to include in the doc-string.
Also, the function always raises an exception. I believe this is because it fails this check:
https://github.com/checkmarx-ts/checkmarx-python-sdk/blob/17d2ef6f9ecfc51930f9a7a0f2a50e8d17fad518/CheckmarxPythonSDK/CxRestAPISDK/ScansAPI.py#L911
and all other else blocks.
OK = http.HTTPStatus.OK = 200, but this API call returns 204. 
Probably should be updated to NO_CONTENT. Or just use `if r.ok` which returns `True` for all 2XX.

**Comment by cx-happy-yang** [comment]
Thanks for reporting the bug. Will fix it today.

**Comment by cx-happy-yang** [comment]
HI @Apipia ,

For API  "/cxrestapi/sast/results/tickets", the return response code is changed to NO_CONTENT (http status code 204).

Please upgrade to latest version, v0.2.3.

Let me know how it works.

Thanks.

**Comment by cx-happy-yang** [comment]
The original document for this API comes from [here](https://checkmarx.atlassian.net/wiki/spaces/KC/pages/564494706/Assign+Ticket+to+Scan+Results+-+POST+sast+results+tickets+v8.8.0+and+up)

resultsId=[string] – Unique Id of the result. ResultsId is made up of the Scan Id and Path Id (example: ScanId = 1000025, PathId = 12, therefore ResultsId = 1000025-12)

![image](https://user-images.githubusercontent.com/30431255/112452337-7e14d180-8d91-11eb-95d7-4d1745b1156b.png)

When we open a ticket from Web Portal, it will create an issue in JIRA. The **Ticket ID** shows the JIRA ticket key (like **PPSCDM-1**). When we call this API with parameters like { "resultsId": "1000004-1", "ticketId": "10055"}, 10055 is the JIRA ticket Id for this issue. Then the column **Ticket ID** in Cx Portal will be changed to 10055.

**Comment by Apipia** [comment]
Thanks! I'll upgrade and take a look.
I'd also like to mention that the function is a bit misleading, or possibly an error. The Docstring says that result_id should be a string. However, this line:
https://github.com/checkmarx-ts/checkmarx-python-sdk/blob/17d2ef6f9ecfc51930f9a7a0f2a50e8d17fad518/CheckmarxPythonSDK/CxRestAPISDK/ScansAPI.py#L898

Will turn it into a list of characters: ["1", "0", "0", "0", "0", "2", "5", "-", "1", "2"]. I get around this by simply passing my result_id in as a list:  `scan_api.assign_ticket_to_scan_result(["1000004-1"], "10055")`

**Comment by cx-happy-yang** [comment]
I see. 

Just made a change to use 

`"resultsId": [results_id],`

You can now use a string instead of an array.

**Comment by Apipia** [comment]
Great thank you!
