### ISSUE TITLE
Checkmarx Python SDK - SSL Verification

### ISSUE THREAD

**Issue by pkaffij2008** [checkmarx-ts/checkmarx-python-sdk#3]
During a routing development and test, I encountered a SSL verification error from the development environment. My question is, can add an ignore SSL verification within the SDK?
requests.exceptions.SSLError: HTTPSConnectionPool(host='<dev-hostname>', port=443): Max retries exceeded with url: /cxrestapi/auth/identity/connect/token (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

**Comment by cx-happy-yang** [comment]
@pkaffij2008  

I have added the verify option (default to False) for all HTTP requests in the CheckmarxPythonSDK.

Please use command ` pip install -U CheckmarxPythonSDK` to upgrade your Checkmarx Python SDK to version 0.0.4. And test again.

Let me know if it works for you.

Thanks.

**Comment by pkaffij2008** [comment]
Happy –

Thank you for the quick turn-around. I was able to get pass the SSL verification. Is it normal to see the scan status stock at getting scan details by scan id? See attached images.
scan_id: 1030945
9. get scan details by scan id

Thank you
../chmod 600
Patrick K. Johnson Jr.
Sr. DevSecOps Engineer
AWS SysOps & DevOps Pro
m: 571.302.6429
[cid:image002.png@01D57E30.AD16CBE0]
#wearebakerhughes
[sysops-cert_150x150]

**Comment by cx-happy-yang** [comment]
@pkaffij2008 
Sorry,  I can't get the image.  Does not bother without the images. 

You are using examples script. You see step 9, get scan details by scan id stock for a while until the status becomes Finished or Failed, because it's checking the scan status of this scan, for a small scan it takes a few minutes.  For a large scan it takes more time.  Depends on how much LOC for your project. 

Happy

**Comment by cx-happy-yang** [comment]
I saw the images in Sales Force.

**Comment by pkaffij2008** [comment]
Happy, this is good. I'll start the scan once more, and wait for a status.

Patrick

**Comment by pkaffij2008** [comment]
Happy –

Apologies for the late response, but all features of the SDK worked as expected. We can close this ticket.
Next, is the integration with authentication using SSO or how to authenticate if a GitHub repository requires token access or login. Any thoughts?

Patrick

**Comment by cx-happy-yang** [comment]
For your questions:
[1] is the integration with authentication using SSO?
Checkmarx support SSO via LDAP and SAML.  Please check [LDAP Single Sign On](https://checkmarx.atlassian.net/wiki/spaces/KC/pages/9863218/Configuring+Single+Sign-On)  and [SAML Single Sign On](https://checkmarx.atlassian.net/wiki/spaces/KC/pages/103252319/Login+using+SAML+Single+Sign-on) .

But for REST API,  even when SSO is enabled for the web client, you must use an application user and not an active directory user for REST API. Check more info about using REST API with this [link](https://checkmarx.atlassian.net/wiki/spaces/KC/pages/1187774721/Using+the+CxSAST+REST+API+v8.6.0+and+up) .

[2] how to authenticate if a GitHub repository requires token access or login?
For GitHub repo with token authentication, please use repository URL like this 

 `https://<Token>@github.com/<AccountName>/<RepositoryName>.git`

For more info about Git Integration, please check this [link](https://checkmarx.atlassian.net/wiki/spaces/KC/pages/220923066/Configuring+a+Project+with+Git+Integration+v8.6.0+and+up) .

Happy
