### ISSUE TITLE
CxSCA: How to renew token when 401 unauthorized

### ISSUE THREAD

**Issue by davidmorabito** [checkmarx-ts/checkmarx-python-sdk#32]
API documentation states that the token expires after 1 hour. I see most of the API verbs use the annotation 
```@retry_when_unauthorized```
But my script ends when the method raises the ValueError exception instead of retrying and renewing the token:
```
scans = get_all_scans_associated_with_a_project(project_id)
# Output
# ValueError: ('HttpStatusCode: 401', 'ErrorMessage: {"message":"Unauthorized"}')
```
Any thoughts?

**Comment by cx-happy-yang** [comment]
Hi @davidmorabito ,

Thank you for reporting this issue. It's indeed some error I have been made. Now it's fixed.

Please upgrade your Checkmarx Python SDK to latest version v0.4.2. 

Let me know if it works for you.

Best regards.

**Comment by davidmorabito** [comment]
Thanks, now works like charm!
