### ISSUE TITLE
Add support for CxSAST Reporting Service API

### ISSUE THREAD

**Issue by cx-james-bostock** [checkmarx-ts/checkmarx-python-sdk#40]
It would be good if the Checkmarx Python SDK added support for the CxSAST Reporting Service API (see [here](https://checkmarx.atlassian.net/wiki/spaces/RS/pages/5860130923/APIs)).

See also [CxSAST Reporting Service - How to use it](https://checkmarx.atlassian.net/wiki/spaces/AA/pages/6166511840/CxSAST+Reporting+Service+-+How+to+use+it)

**Comment by cx-happy-yang** [comment]
Thank you James. I will look into it.

**Comment by cx-happy-yang** [comment]
Hi James, 

Just make a new release.

it is supported from version 0.4.6.

Best regards.

**Comment by cx-happy-yang** [comment]
CxReporting API supported.
