### ISSUE TITLE
Command line options handling breaks users of the SDK

### ISSUE THREAD

**Issue by cfzlp** [checkmarx-ts/checkmarx-python-sdk#5]
The way command line options are being handled prevents the SDK from being used in applications that use command line options themselves. Or even running tests with pytest using options.

Any options that are not expected by the SDK cause the program to fail with:

`error: no such option: --option`

The SDK should either not use command line options at all or ignore command line options it does not expect and proceed without throwing exceptions.

**Comment by cx-happy-yang** [comment]
@cfzlp  I will look into this issue. Update you soon.

**Comment by cx-happy-yang** [comment]
@cfzlp follow your advice, I ignore the unknown command line options. version 0.0.9 should work for you.

**Comment by cfzlp** [comment]
Awesome!

Thank you, @HappyY19.
