### ISSUE TITLE
How to configure timeout?

### ISSUE THREAD

**Issue by davidmorabito** [checkmarx-ts/checkmarx-python-sdk#53]
Hi, have several issues with the server timing out. 
How can I change the timeout value?

Thanks

**Comment by cx-happy-yang** [comment]
Hi @davidmorabito , 

Thank you for report this issue. Yes. currently there is no timeout for all the HTTP request. Will add it in nex rlease.

I will follow the [Python Requests document](https://docs.python-requests.org/en/latest/user/advanced/#timeouts) to set the timeout parameter.

**Comment by cx-happy-yang** [comment]
Now by default the timeout is 60 seconds.

in the config.ini each section, you can set `timeout = 60` to define timeout
