### ISSUE TITLE
Provide password to auth class

### ISSUE THREAD

**Issue by davidmorabito** [checkmarx-ts/checkmarx-python-sdk#54]
We have a script that uses .env to define all environment variables that are loaded in runtime using python-dotenv. Would be great if you can initialize the auth class and provide password like:

```
os.environ.get('CHECKMARX_TOKEN')
```
This approach also helps if you are using docker and don't want to define secrets on the docker-compose file

**Comment by cx-happy-yang** [comment]
Hi @davidmorabito , 

I will look into this issue, and get back to you.

**Comment by cx-happy-yang** [comment]
Hi @davidmorabito ,

Checkmarx Python SDK does support read from environment variables. You can define environment variables by using the variables listed [here](https://github.com/checkmarx-ts/checkmarx-python-sdk#option-2-using-environment-variables-or-command-line-arguments).

For example, define your CxSAST environment varaibles by using `cxsast_base_url=***`

The environment variables value would override the value from config file (config.ini or config.json). 

If you do not want to use config file, just ignore it, you can just use the environment variables.
