### ISSUE TITLE
The User class is missing the creationDate property

### ISSUE THREAD

**Issue by csassaman-els** [checkmarx-ts/checkmarx-python-sdk#91]
Is it possible to have the `creationDate` property added to the `User` class? I can see it is returned in the response for the call to `/cxrestapi/auth/Users` but the value is never assigned to a property on the object. Thanks!

**Comment by cx-happy-yang** [comment]
Hi @csassaman-els ,

Thanks for reporting the issue. Will fixed the issue today. It will be in version starting from v0.6.2.

Best regards.
