### ISSUE TITLE
Any plans to support json or sarif output

### ISSUE THREAD

**Issue by dszortyka** [checkmarx-ts/checkmarx-python-sdk#94]
Hey there, 
We are testing both cx-flow and Python SDK to integrate checkmarx to our scaning process. 
Is there any plans to support json or sarif output?
Thanks,
Daniel

**Comment by dszortyka** [comment]
Just in case anyone else is interested on this. I found this repo, a single commit... but it's serving its purpose.
https://github.com/xgoffin/cxxml_to_sarif_standalone

**Comment by cx-happy-yang** [comment]
Hi @dszortyka ,

Appreciate your good idea. I will work on this.

Best regards.
Happy

**Comment by cx-happy-yang** [comment]
Hi @dszortyka ,

I have add the support it in module  CheckmarxPythonSDK/CxRestAPISDK/CxSastXML and  CheckmarxPythonSDK/external/sarif.

You can follow https://github.com/checkmarx-ts/checkmarx-python-sdk/blob/master/tests/external/test_sarif.py to do test.

Let me know if it works for you, or any new issues.
Best regards
Happy

**Comment by dszortyka** [comment]
Thanks @HappyY19 , it's working fine!! Appreciate your quick response and attention to this request. 
Cheers,
-Daniel
