### ISSUE TITLE
Calls to get_windows_domain_user_entries_by_search_criteria() do not return the correct properties on the User object

### ISSUE THREAD

**Issue by csassaman-els** [checkmarx-ts/checkmarx-python-sdk#98]
When debugging, I can see that the call to `/cxrestapi/auth/WindowsDomains` returns the correct data, but the JSON has the following keys: `username`, `firstname`, `lastname`, `email`.

The `construct_user()` method is looking for `userName`, `firstName`, and `lastName`, so the property values do not get assigned to the User object that is returned.

Thanks!

**Comment by cx-happy-yang** [comment]
Thanks for submitting the pull request. 

I will make a new release.
